spring:
  application:
    name: ChatClient
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        use-tls: false
        collection-name: movie-collection
        content-field-name: text
        initialize-schema: true
    mcp:
      client:
        enabled: true
        streamable-http:
          connections:
            local-mcp:
              url: http://localhost:8081
              endpoint: /mcp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=aichatclient
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update